packages:
  - packages/signers/*
  - packages/json-rpc/*
  - packages/*
  - examples/*
  - integration-tests/*
  - scripts/bump
allowBuilds:
  '@swc/core': true
  esbuild: true
  node-hid: true
  usb: true
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - node-hid
  - sqlite3
  - usb
