packages:
  - packages/signers/*
  - packages/json-rpc/*
  - packages/*
  - examples/*
  - integration-tests/*
  - scripts/bump
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - node-hid
  - sqlite3
  - usb
