import {
  getDynamicBuilder,
  getLookupFn,
  MetadataLookup,
} from "@polkadot-api/metadata-builders"
import {
  decAnyMetadata,
  Enum,
  unifyMetadata,
} from "@polkadot-api/substrate-bindings"
import { fromHex, mergeUint8, toHex } from "@polkadot-api/utils"
import type { TxCreatorBindings } from "@polkadot-api/signers-common"
import { concat, NEVER, of } from "rxjs"
import type { ChainDefinition } from "./descriptors"
import type { OfflineTxEntry } from "./tx"
import type { OfflineApi } from "./types"
import { TxPayloadV1 } from "@polkadot-api/polkadot-signer"

const getOfflineExtensions = (
  genesis: string,
  lookupFn: MetadataLookup,
  builder: ReturnType<typeof getDynamicBuilder>,
  { nonce, mortality }: { nonce: number; mortality?: any },
): TxPayloadV1["extensions"] => {
  const nonceType = lookupFn.metadata.extrinsic.extensions["CheckNonce"]?.type
  const nonceExt =
    nonceType != null
      ? [
          {
            id: "CheckNonce",
            extra: toHex(builder.buildDefinition(nonceType).enc(nonce)),
            additionalSigned: "0x",
          },
        ]
      : []
  // only set mortality if not set by the user
  const mortalityExt =
    mortality == null &&
    lookupFn.metadata.extrinsic.extensions["CheckMortality"]
      ? [{ id: "CheckMortality", extra: "0x00", additionalSigned: genesis }]
      : []
  return [...mortalityExt, ...nonceExt]
}

const createOfflineTxEntry = <Arg extends {} | undefined>(
  pallet: string,
  name: string,
  genesisHex: string,
  metadataRaw: Uint8Array,
  lookupFn: MetadataLookup,
  dynamicBuilder: ReturnType<typeof getDynamicBuilder>,
): OfflineTxEntry<Arg> => {
  let codecs
  try {
    codecs = dynamicBuilder.buildCall(pallet, name)
  } catch {
    throw new Error(`Runtime entry Tx(${pallet}.${name}) not found`)
  }
  const { location, codec } = codecs
  const locationBytes = new Uint8Array(location)

  return (arg: Arg) => {
    const encodedData = mergeUint8([locationBytes, codec.enc(arg)])

    return {
      encodedData,
      decodedCall: Enum(pallet, Enum(name, arg)),
      create: async (creator, txOptions) => {
        return fromHex(
          await creator(
            {
              callData: toHex(encodedData),
              context: {
                metadata: toHex(metadataRaw),
                bestBlockHash: genesisHex,
                bestBlockHeight: 0,
                genesisHash: genesisHex,
                token: null,
              },
              extensions: getOfflineExtensions(
                genesisHex,
                lookupFn,
                dynamicBuilder,
                txOptions,
              ),
              signer: null,
              txExtVersion: null,
              version: 1,
            },
            txOptions,
            false,
          ),
        )
      },
    }
  }
}

/**
 * Asynchronously create an instance of `OfflineApi`.
 * OfflineApi allows to create and sign transactions and access chain constants.
 *
 * @param chainDefinition  Pass descriptors from `@polkadot-api/descriptors`
 *                         generated by `papi` CLI.
 */
export const getOfflineApi: <D extends ChainDefinition>(
  chainDefinition: D,
) => Promise<OfflineApi<D>> = async ({ genesis: genesisHex, getMetadata }) => {
  if (!genesisHex) throw new Error("Missing genesis hash")
  const metadataRaw = await getMetadata()
  const metadata = unifyMetadata(decAnyMetadata(metadataRaw))
  const lookupFn = getLookupFn(metadata)
  const dynamicBuilder = getDynamicBuilder(lookupFn)

  const getPallet = (name: string) =>
    metadata.pallets.find((p) => p.name === name)

  const target = {}
  const createProxy = (propCall: (prop: string) => unknown) =>
    new Proxy(target, {
      get(_, prop) {
        return propCall(prop as string)
      },
    })

  const createProxyPath = <T>(pathCall: (a: string, b: string) => T) => {
    const cache: Record<string, Record<string, T>> = {}
    return createProxy((a) => {
      if (!cache[a]) cache[a] = {}
      return createProxy((b) => {
        if (!cache[a][b]) cache[a][b] = pathCall(a, b)
        return cache[a][b]
      })
    }) as Record<string, Record<string, T>>
  }

  const constants = createProxyPath((pallet, name) => {
    const constant = getPallet(pallet)?.constants.find((c) => c.name === name)
    if (!constant)
      throw new Error(`Runtime entry Constant(${pallet}.${name}) not found`)
    return dynamicBuilder.buildConstant(pallet, name).dec(constant.value)
  })

  const tx = createProxyPath((pallet, name) =>
    createOfflineTxEntry(
      pallet,
      name,
      genesisHex,
      metadataRaw,
      lookupFn,
      dynamicBuilder,
    ),
  )

  const finalized = {
    hash: genesisHex,
    parent: "0x" + "0".repeat(64),
    number: 0,
  }
  const tips = [finalized]
  const txCreatorBindings: TxCreatorBindings = {
    blocks: concat(
      of(
        { type: "newTip" as const, finalized, tips, newTip: finalized },
        { type: "finalized" as const, finalized, tips },
      ),
      NEVER,
    ),
    call: async () => {
      throw new Error("OfflineApi cannot perform runtime calls")
    },
  }

  return { constants, tx, txCreatorBindings } as any
}
