export const Problem = {
  ANCIENT_METADATA: "ANCIENT_METADATA",
  MISSING_MODERN_METADATA: "MISSING_MODERN_METADATA",
  MISSING_RUNTIME_APIS: "MISSING_RUNTIME_APIS",
  DEV_APIS_PRESENT: "DEV_APIS_PRESENT",
  MISSING_CHECK_METADATA_HASH_EXTENSION:
    "MISSING_CHECK_METADATA_HASH_EXTENSION",
  DIFFERENT_METADATA_HASHES: "DIFFERENT_METADATA_HASHES",
  WRONG_OR_MISSING_METADATA_HASH: "WRONG_OR_MISSING_METADATA_HASH",
} as const

export type Problem = (typeof Problem)[keyof typeof Problem]
