// Generated by @polkadot-api/cli
import { getPalletCreator } from "@polkadot-api/substrate-bindings"
import type { ArgsWithoutPayloadCodec } from "@polkadot-api/substrate-bindings"
import type {
  cPallet_balancesPalletEventTransfer,
  cPallet_balancesPalletEventDeposit,
  cPallet_balancesPalletEventWithdraw,
  cPallet_balancesPalletCallTransfer_keep_aliveTupled,
} from "./westend-types.d.ts"

const CONST = "const"

const EVENT = "event"

const ERROR = "error"

const BalancesCreator = getPalletCreator("Balances")

const BalancesTransferEvent = BalancesCreator.getPayloadDescriptor(
  EVENT,
  10361351692762254388n,
  "Transfer",
  {} as unknown as cPallet_balancesPalletEventTransfer,
)

const BalancesDepositEvent = BalancesCreator.getPayloadDescriptor(
  EVENT,
  6307645739519015793n,
  "Deposit",
  {} as unknown as cPallet_balancesPalletEventDeposit,
)

const BalancesWithdrawEvent = BalancesCreator.getPayloadDescriptor(
  EVENT,
  6307645739519015793n,
  "Withdraw",
  {} as unknown as cPallet_balancesPalletEventWithdraw,
)

const Balancestransfer_keep_aliveCall = BalancesCreator.getTxDescriptor(
  10049767239352345970n,
  "transfer_keep_alive",
  [],
  [],
  {
    len: 2,
  } as ArgsWithoutPayloadCodec<cPallet_balancesPalletCallTransfer_keep_aliveTupled>,
)

const constantDescriptors: [] = []

const storageDescriptors: [] = []

const eventDescriptors: [
  typeof BalancesTransferEvent,
  typeof BalancesDepositEvent,
  typeof BalancesWithdrawEvent,
] = [BalancesTransferEvent, BalancesDepositEvent, BalancesWithdrawEvent]

const errorDescriptors: [] = []

const callDescriptors: [typeof Balancestransfer_keep_aliveCall] = [
  Balancestransfer_keep_aliveCall,
]
const result: [
  typeof constantDescriptors,
  typeof storageDescriptors,
  typeof eventDescriptors,
  typeof errorDescriptors,
  typeof callDescriptors,
] = [
  constantDescriptors,
  storageDescriptors,
  eventDescriptors,
  errorDescriptors,
  callDescriptors,
]

export default result
